# Generated by Django 3.0.6 on 2020-06-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
